##########################################
##        ColinZeDev's Kitty Conf       ##
##                v0.0.2                ##
##             Mar. 05, 2026            ##
##########################################


# Window Settings
remember_window_size              no
initial_window_width              125c
initial_window_height             35c
background_opacity                0.452
background_blur                   18

# Cursor Settings
cursor_shape                      block
cursor_blink_interval             0.5
cursor_stop_blinking_after        15.0
cursor_trail                      11
cursor_trail_start_threshold      0
cursor_trail_decay                0.001 0.008

# Font Settings
font_family                       Fira Code
bold_font                         Fira Code Bold
italic_font                       Fira Code Italic
font_size                         11.2

# Scrollback Settings
scrollback_lines                  10000
scrollback_pager                  less
scrollback_pager_history_size     0

# Performance Settings
sync_to_monitor                   yes

# Visual Settings
dim_opacity                       0.75
inactive_text_alpha               0.8

# Misc Settings
allow_remote_control              yes
enable_audio_bell                 no
strip_trailing_spaces             smart
confirm_os_window_close           0
tab_title_template                {title} # other parts of this are in zshrc
shell_integration                 no-title no-cursor
