backend = "glx"
vsync = true

corner-radius = 10
rounded-corners-exclude = [
    "class_g = 'Polybar'",
    "class_g = 'librewolf'",
    "class_g = 'Code'",
    "class_g = 'Sober'"
];

shadow = true
shadow-radius = 12
shadow-opacity = 0.6
shadow-offset-x = -8
shadow-offset-y = -8
shadow-exclude = [
    "class_g = 'Polybar'"
]

fading = true
fade-in-step = 0.6
fade-out-step = 0.6
fade-delta = 3
no-fading-openclose = false

animations = true
animation-stiffness = 146
animation-dampening = 22.2
animation-mass = 1
animation-for-open-window = "zoom"
animation-for-unmap-window = "zoom"
animation-for-transient-window = "slide-up"

inactive-opacity = 0.92
active-opacity = 1.0
frame-opacity = 1.0

blur-method = "dual_kawase"
blur-strength = 5
blur-background = true
blur-background-frame = true
blur-background-exclude = [
    "class_g = 'Polybar'"
]
blur-background-include = [
    "class_g = 'Dunst'"
]

window-shader-fg-rule = [
    "default:class_g = 'Dunst'"
]
